[package]
name = "treelink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["blocking"] }
scraper = "0.14.0"
